'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import { SearchComponent as SearchComponentElement, defineCustomElement as defineSearchComponent } from "stencil-library/dist/components/search-component.js";

type SearchComponentEvents = NonNullable<unknown>;

export const SearchComponent: StencilReactComponent<SearchComponentElement, SearchComponentEvents> = /*@__PURE__*/ createComponent<SearchComponentElement, SearchComponentEvents>({
    tagName: 'search-component',
    elementClass: SearchComponentElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SearchComponentEvents,
    defineCustomElement: defineSearchComponent
});
