/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SearchComponent {
        "apiKey": string;
        "fontFamily": string;
        "fontSize": string;
        "fontStyle": string;
        "themeColor": string;
        "userId": string;
        "variant": number;
        "widthDimension": string;
    }
}
declare global {
    interface HTMLSearchComponentElement extends Components.SearchComponent, HTMLStencilElement {
    }
    var HTMLSearchComponentElement: {
        prototype: HTMLSearchComponentElement;
        new (): HTMLSearchComponentElement;
    };
    interface HTMLElementTagNameMap {
        "search-component": HTMLSearchComponentElement;
    }
}
declare namespace LocalJSX {
    interface SearchComponent {
        "apiKey"?: string;
        "fontFamily"?: string;
        "fontSize"?: string;
        "fontStyle"?: string;
        "themeColor"?: string;
        "userId"?: string;
        "variant"?: number;
        "widthDimension"?: string;
    }
    interface IntrinsicElements {
        "search-component": SearchComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "search-component": LocalJSX.SearchComponent & JSXBase.HTMLAttributes<HTMLSearchComponentElement>;
        }
    }
}
